#pragma once

namespace IMG {
enum {
t_metrix,
t_ball,
};
}

namespace SHADER {
enum {
f_sprite,
v_sprite,
};
}

namespace ATLAS {
enum {
shoot,
};
}

namespace shoot {
enum {
DUCK_BACK_PNG,
DUCK_BROWN_PNG,
DUCK_OUTLINE_BACK_PNG,
DUCK_OUTLINE_BROWN_PNG,
DUCK_OUTLINE_TARGET_BROWN_PNG,
DUCK_OUTLINE_TARGET_WHITE_PNG,
DUCK_OUTLINE_TARGET_YELLOW_PNG,
DUCK_OUTLINE_WHITE_PNG,
DUCK_OUTLINE_YELLOW_PNG,
DUCK_TARGET_BROWN_PNG,
DUCK_TARGET_WHITE_PNG,
DUCK_TARGET_YELLOW_PNG,
DUCK_WHITE_PNG,
DUCK_YELLOW_PNG,
RIFLE_PNG,
RIFLE_RED_PNG,
SHOT_BLUE_LARGE_PNG,
SHOT_BLUE_SMALL_PNG,
SHOT_BROWN_LARGE_PNG,
SHOT_BROWN_SMALL_PNG,
SHOT_GREY_LARGE_PNG,
SHOT_GREY_SMALL_PNG,
SHOT_YELLOW_LARGE_PNG,
SHOT_YELLOW_SMALL_PNG,
STICK_METAL_PNG,
STICK_METAL_BROKEN_PNG,
STICK_METAL_OUTLINE_PNG,
STICK_METAL_OUTLINE_BROKEN_PNG,
STICK_WOOD_PNG,
STICK_WOODFIXED_PNG,
STICK_WOODFIXED_OUTLINE_PNG,
STICK_WOOD_BROKEN_PNG,
STICK_WOOD_OUTLINE_PNG,
STICK_WOOD_OUTLINE_BROKEN_PNG,
TARGET_BACK_PNG,
TARGET_BACK_OUTLINE_PNG,
TARGET_COLORED_PNG,
TARGET_COLORED_OUTLINE_PNG,
TARGET_RED1_PNG,
TARGET_RED1_OUTLINE_PNG,
TARGET_RED2_PNG,
TARGET_RED2_OUTLINE_PNG,
TARGET_RED3_PNG,
TARGET_RED3_OUTLINE_PNG,
TARGET_WHITE_PNG,
TARGET_WHITE_OUTLINE_PNG,
};
}

